# action.yaml
name: 'Cross Platform Blog Publish'
description: 'To publish blogs at different blogging websites simultaneously by uploading a markdown to a github repository.'
author: Sarthak Narayan, Arpit Gupta

inputs:
  website:
    description: 'Website to which you want to publish'
    required: true
  log_level:
    description: 'Log level for the logger'
    required: true
  token:
    description: 'The token to use to access the blogging website'
    required: true

branding:
  icon: 'upload-cloud'
  color: 'gray-dark'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.website }}
    - ${{ inputs.log_level }}
    - ${{ inputs.token }}