# action.yaml
name: 'Blog Custom Github Action'
description: 'Action Testing'

inputs:
  website:
    description: 'Website to which you want to publish'
    required: true
  token_github:
    description: 'The token to use to access the GitHub API'
    required: true
  token:
    description: 'The token to use to access the blogging website'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.website }}
    - ${{ inputs.token_github }}
    - ${{ inputs.token }}